### ISSUE TITLE
Make new project 

### ISSUE THREAD

**Issue by iopoio** [UnRyongPark/multilang.dev.issues#1]
새프로젝트 만들기에서 sumit 누르면 오류 발생 (오류팝업)

~파일첨부가 없다니 ㅂㄷㅂㄷ~

있그나?!
![newprojent_bug01](https://user-images.githubusercontent.com/70686682/92082105-1308ab00-edff-11ea-9fcc-a9a13a72ff31.jpg)
![newprojent_bug02](https://user-images.githubusercontent.com/70686682/92082119-18fe8c00-edff-11ea-8a22-7992eb94c833.jpg)

**Comment by UnRyongPark** [comment]
@iopoio 대략 확인해보니 수정중에 있던 오류인 것 같아욥 :D 파일 첨부는 프로젝트 다 만들고 있습니다요
이제는 해-결
