### ISSUE TITLE
[FE] Slack Incomming Webhook 데이터 바인딩 요청

### ISSUE THREAD

**Issue by UnRyongPark** [UnRyongPark/multilang.dev.issues#22]
**Describe the bug**
서버에서 응답 값에는 웹훅 주소가 리턴되는데 클라에서 적용이 안됩니당.
저장하는 쪽도 확인 부탁드려요.(서버에서 받아주도록 처리는 되어있습니다.)

예외처리로는 https://가 반드시 붙어있어야 하도록 처리 부탁드립니다.

**To Reproduce**
1. 프로젝트 수정 페이지로 이동
2. 슬랙 인커밍웹훅 주소 등록

**Expected behavior**
등록 후 결과가 정상 반영되어야 함.

**Screenshots**
![image](https://user-images.githubusercontent.com/6115168/127766354-cb8ded34-eec1-4a86-9fa6-1944ae8cb3b6.png)

**Comment by dev-yeojin** [comment]
프론트쪽에서 사용하는 변수명이랑 맞지않아서 이슈가 있었네요. 
수정완료하였습니다!
